baseURL = 'https://www.dr-elliot.com/'
languageCode = 'en-us'
title = "Dr. Elliot"
theme = "rusty-typewriter"

enableRobotsTXT = true

# rtwt = Rusty Typewriter Theme
[params.rtwt.side.home]
taxonomies = ['tags','series']
countTaxonomy = 3

[taxonomies]
tag = 'tags'
topic = 'topics'
series = 'series'

[params.author]
name = 'Dr. Elliot'

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 1

[[menus.main]]
name = 'Lumina'
pageRef = '/lumina/lumina.md'
weight = 2

[[menus.main]]
name = 'About'
pageRef = '/about/aboutme.md'
weight = 3

[outputFormats]
 [outputFormats.SearchIndex]
  mediaType = "application/json"
  baseName = "searchindex"
  isPlainText = true
  notAlternative = true

[mediaTypes]
 [mediaTypes."application/json"]
  suffixes = ["json"]

[outputs]
 home = ["HTML","RSS", "SearchIndex"]

